import { Link } from 'react-router-dom'

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 680, margin: '48px auto', padding: '0 16px 64px' }}>

      <h1 style={{ fontSize: '1.75rem', marginBottom: 8 }}>Terms of Service</h1>
      <p className="text-muted" style={{ fontSize: '0.9rem', marginBottom: 40 }}>
        Last updated April 2026 · S3C-Tool is open source —{' '}
        <a
          href="https://github.com/askmcconnell/s3c-tool"
          target="_blank"
          rel="noopener noreferrer"
          style={{ color: 'var(--accent)' }}
        >
          audit the code yourself
        </a>
      </p>

      <Section title="Acceptance">
        <p>
          By creating an account or using S3C-Tool, you agree to these terms. If you do not
          agree, do not use the service. These terms apply to the web application at
          askmcconnell.com/s3c/ and all associated scanner scripts.
        </p>
      </Section>

      <Section title="What S3C-Tool is">
        <p>
          S3C-Tool is a software supply chain security tool. You upload a software inventory
          CSV generated by the scanner scripts; S3C-Tool cross-references the inventory against
          a shared end-of-life (EOL) reference database and returns a report identifying
          end-of-life, unsupported, or unpatched software.
        </p>
        <p style={{ marginTop: 12 }}>
          S3C-Tool is a research aid, not a substitute for professional security assessment.
          EOL determinations are based on publicly available data, community research, and
          AI-assisted lookups. Results may be incomplete or incorrect.
        </p>
      </Section>

      <Section title="Accounts">
        <BulletList items={[
          ['Registration', 'You must provide a valid email address. One account per person or organization.'],
          ['Security', 'You are responsible for keeping your account token confidential. Do not share tokens.'],
          ['Acceptable use', 'Use S3C-Tool only for lawful purposes on systems you own or have authorization to scan.'],
          ['Termination', 'We may suspend or terminate accounts that violate these terms or abuse the service.'],
        ]} />
      </Section>

      <Section title="Scanner scripts">
        <p>
          The scanner scripts (s3c_scan_mac.py, s3c_scan_linux.py, s3c_scan_windows.ps1) are
          open source under the MIT license. You may run them only on systems you own or are
          explicitly authorized to scan. The scripts do not transmit data automatically —
          upload is a manual step you initiate.
        </p>
      </Section>

      <Section title="Data you upload">
        <p style={{ marginBottom: 12 }}>
          By uploading an inventory CSV you represent that:
        </p>
        <BulletList items={[
          ['Authorization', 'You have the right to collect and upload this software inventory data.'],
          ['Accuracy', 'The CSV was generated by an S3C-Tool scanner script or conforms to the documented format.'],
          ['No sensitive data', 'Hostnames are hashed by the scanner before upload. Do not manually include un-hashed hostnames, IP addresses, or credentials in any CSV field.'],
        ]} />
      </Section>

      <Section title="Shared reference database">
        <p>
          When S3C-Tool resolves an EOL status for a software product, that result is added
          to the shared reference database. Shared entries contain only software name, vendor,
          version, platform, EOL status, and source — no user identifiers, no hostname hashes,
          and no account information. By using S3C-Tool you consent to your resolved EOL
          results contributing to this shared database.
        </p>
      </Section>

      <Section title="AI-assisted research">
        <p>
          S3C-Tool uses AI models (Claude Haiku, GPT-4o-mini, Gemini Flash) to research EOL
          status for products not found in public databases. AI results are assigned a
          confidence score and subject to expiry and re-verification. AI models can be wrong.
          Do not make security decisions based solely on AI-sourced EOL determinations without
          independent verification.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          S3C-Tool is provided <strong>"as is"</strong> without warranty of any kind. We make
          no guarantees about the accuracy, completeness, or timeliness of EOL data. The
          reference database may lag behind vendor announcements. Use the results as a starting
          point for investigation, not a definitive security audit.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Ask McConnell and S3C-Tool contributors are
          not liable for any damages arising from your use of the service, including but not
          limited to security incidents, data loss, or decisions made based on EOL reports.
          Your use of S3C-Tool is at your own risk.
        </p>
      </Section>

      <Section title="Voluntary contributions">
        <p>
          S3C-Tool is free to use. Optional contributions via Stripe are voluntary and
          non-refundable. Contributions do not create any service-level obligations or
          unlock premium features — they simply help cover operating costs.
        </p>
      </Section>

      <Section title="Open source">
        <p>
          S3C-Tool source code is published on{' '}
          <a
            href="https://github.com/askmcconnell/s3c-tool"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'var(--accent)' }}
          >
            GitHub
          </a>{' '}
          under the MIT license. You are free to fork, self-host, and modify the code subject
          to the MIT license terms. The hosted service at askmcconnell.com/s3c/ is operated
          separately from the open source project.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms at any time. Continued use of S3C-Tool after a change
          constitutes acceptance of the updated terms. The "Last updated" date at the top of
          this page will reflect the most recent revision.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms can be sent to{' '}
          <a href="mailto:jim@askmcconnell.com" style={{ color: 'var(--accent)' }}>
            jim@askmcconnell.com
          </a>.
        </p>
      </Section>

      <p className="text-muted" style={{ fontSize: '0.8rem', marginTop: 32, textAlign: 'center' }}>
        <Link to="/privacy" style={{ color: 'var(--accent)' }}>Privacy & Data Practices</Link>
        {' · '}
        <a href="https://github.com/askmcconnell/s3c-tool" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--text-muted)' }}>
          Open source on GitHub
        </a>
      </p>

    </div>
  )
}


function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: 12, paddingBottom: 8,
                   borderBottom: '1px solid var(--border)' }}>
        {title}
      </h2>
      <div style={{ fontSize: '0.92rem', lineHeight: 1.75, color: 'var(--text)' }}>
        {children}
      </div>
    </div>
  )
}


function BulletList({ items }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      {items.map(([label, desc]) => (
        <div key={label} style={{ display: 'flex', gap: 12 }}>
          <div style={{ color: 'var(--accent)', flexShrink: 0, paddingTop: 2 }}>→</div>
          <div>
            <strong>{label}</strong>
            {desc ? <> — {desc}</> : null}
          </div>
        </div>
      ))}
    </div>
  )
}
